### ISSUE TITLE
no more smooth zoom?

### ISSUE THREAD

**Issue by FyreModServer** [space-commits/SPT-Realism-Mod-Client#32]
couldn't find the option, couldn't find/search for it in the bepinex menu.
Migrated from 3.7.1 to 3.7.4 and latest install and now I can't find it. There used to be an option to "use mousewheel" or "hold button with mousewheel" but I checked the release notes and known issues and I haven't seen it labelled.
I'm using the same exact set up through the GUI as I always do.

**Comment by space-commits** [comment]
These features are not part of Realism mod, but FOV Fix + Variable Optics. The option has not changed or been removed.
