### ISSUE TITLE
Getting Type Error when enabling bot changes

### ISSUE THREAD

**Issue by KingSombra231** [space-commits/SPT-Realism-Mod-Client#33]
So whenever i start to turn on Bot changes in the newest version of this mod i get this exact error here:

TypeError: Cannot read properties of undefined (reading '5fd20ff893a8961fc660a954')

I am honestly not sure what is causing this, is there maybe some kind of info i can find somewhere that might help me fix this?

**Comment by space-commits** [comment]
This isn't an issue with the mod itself, please use the mod's support thread on the hub for general user report. This can be caused by incorrect mod set up/configuration, conflicting mods, wrong SPT/EFT/mod version or due to using pirated software.
