### ISSUE TITLE
Unable to load bot's presets

### ISSUE THREAD

**Issue by kakahost** [space-commits/SPT-Realism-Mod-Client#43]
![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/95466263/24273318-c9c9-403e-83cd-b29fb0b24170)

**Comment by kakahost** [comment]
Weapon 5ae08f0a5acfc408fb1398a1 was generated incorrectly, returning to default preset, watch error above.

**Comment by kakahost** [comment]
This thing delays bot's spawn for 10-20 seconds

**Comment by space-commits** [comment]
this isn't an issue, it's just using the default weapon preset. It won't delay bot spawns, that would be a separate issue.
