### ISSUE TITLE
Error: Items must not be empty

### ISSUE THREAD

**Issue by Mimikatz-01** [space-commits/SPT-Realism-Mod-Client#50]
map loading takes about 30 minutes. the server terminal shows these errors.
![Screenshot_41](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/60702145/0bdce2c3-340c-4111-9d03-1f238187d4d4)

**Comment by Mimikatz-01** [comment]
![Screenshot_42](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/60702145/85ec8fef-9ce9-4730-8288-5788f60a786d)
plus this error - even though this file is in place

**Comment by ModTX** [comment]
Same for me. The lastest version SPT Realism. No errors before this ones (they also happen in 1.1.1 ver). Fresh install

![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/168602249/221030dd-c09b-42dd-bdea-f5f98951f585)

![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/168602249/40ebf6d7-f4ec-4d97-a3c0-3bb377d1aa02)

Turning off "Bot loot changes" doestn't help. The only way the mod works is if i disable "Bot changes"
No more mods that affect AI
![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/168602249/f07fe1b4-bc28-41bc-bdd4-f59a4a77354f)

I'm running every .exe with an administrator rights

**Comment by silvagan** [comment]
It seems that this mod is conflicting with Valens Progression for some reason, the bot spawning can be fixed by removing it.

**Comment by space-commits** [comment]
yes, if bot progression is enabled for Realism, installing another mod that also affects bot progression will conflict with it.....
