### ISSUE TITLE
[Project Fika] Flea market tier taking account of last logged in player on server

### ISSUE THREAD

**Issue by drmahorin** [space-commits/SPT-Realism-Mod-Client#51]
Nuff said, tier system is linked into last player logged in on server.
Effect is visible at most in multiplayer, so multiple profiles are online. If player with level 13 log in, tier 2 will be unlocked. If after that dev account with lvl 69 will sign in, all players will gain access to entire flea market. If lvl 1 sign in last, flea market will be empty.

**Comment by space-commits** [comment]
this is not the place for such issues
