### ISSUE TITLE
Issue with Bot Spawning

### ISSUE THREAD

**Issue by DaveJV** [space-commits/SPT-Realism-Mod-Client#55]
**SPT-AKI 3.8.1 + Realism Release Candidate 1.2.0**

With bot changes enabled this text is thrown into the console of the server when attempting to spawn bots.

> TypeError: Cannot convert undefined or null to object
> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at WeightedRandomHelper.getWeightedValue (C:\snapshot\src\helpers\WeightedRandomHelper.ts:28:33)
>     at BotLootGen.genLoot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_loot_serv.ts:100:64)
>     at BotInvGen.myGenerateInventory (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:467:24)
>     at BotGen.myGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:386:35)
>     at BotGen.myPrepareAndGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:324:20)
>     at BotGenerator.prepareAndGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\mod.ts:178:35)
>     at BotController.returnSingleBotFromCache (C:\snapshot\src\controllers\BotController.ts:340:54)
>     at BotController.generate (C:\snapshot\src\controllers\BotController.ts:192:21)
>     at QuestingBots.generateBots (F:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:532:41)
> 
> TypeError: Cannot convert undefined or null to object
> TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at WeightedRandomHelper.getWeightedValue (C:\snapshot\src\helpers\WeightedRandomHelper.ts:28:33)
>     at BotLootGen.genLoot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_loot_serv.ts:100:64)
>     at BotInvGen.myGenerateInventory (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:467:24)
>     at BotGen.myGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:386:35)
>     at BotGen.myPrepareAndGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:324:20)
>     at BotGenerator.prepareAndGenerateBot (F:\Games\SPT\user\mods\SPT-Realism\src\mod.ts:178:35)
>     at BotController.returnSingleBotFromCache (C:\snapshot\src\controllers\BotController.ts:340:54)
>     at BotController.generate (C:\snapshot\src\controllers\BotController.ts:192:21)
>     at QuestingBots.generateBots (F:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:532:41)

Tested with other mods enabled (questing, looting bots) and without any other mods and recreated issue with same error.

![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/38784176/4d582994-d2ee-4c16-8e41-51d38152f35f)

**Comment by space-commits** [comment]
resolved
