### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by kakahost** [space-commits/SPT-Realism-Mod-Client#68]
After second server launch SPT-Realism/config/config.json thrown an syntax error at 3272 position. Turns out it had second "}", which was the issue. 
![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/95466263/f0d53697-b265-4b22-b60d-fc89647b3f14)
After removal of this symbol it launched fine.

**Comment by space-commits** [comment]
that's not a known issue with any of the Realism releases, are you manually editing the config?

**Comment by kakahost** [comment]
I did clean update as mentioned in Test Build 5. That didn't happen anymore. I don't know what happened on that launch, I edit the config using executable app.
