### ISSUE TITLE
can't load other mods, Please help.

### ISSUE THREAD

**Issue by KeaiMazhazha** [space-commits/SPT-Realism-Mod-Client#70]
It used to work fine but for today when I started my serverd realism loaded in red and cant load anything else. if I remove reralism all other mods are able to load. tried to re-download or download older version of realism didn't seems to work. Tried romoving every other mods one by one didn't find a compatible error. Tried change load order around didn't quite do anything either. Wonder what's the problem. Please help.

my mods downloaded are:
AAAArtemTrader
AAArtemEquipment
acidphantasm-harryhideout
AdditionalAkiGifts_0_9_0
aMoxoPixel-Painter
AR-54
ATLAS-GEAR
DanW-SPTQuestingBots
dirtbikercj-removetimegatefromquests-1.0.1
MoxoPixel-BlackCoreMoxoPixel-BlackCore
MoxoPixel-TacticalGearComponent
ServerValueModifier
Virtual's Custom Quest Loader
WTT-Armory-HK417
WTT-Armory-SVD
WTT-LittleDrummerBoy
WTT-PackNStrap
WTT-RogueJustice
WTT-SianydeAndACRiness
WTT-SianydeAndG3iness
WTT-SianydeAndScorpiness
WTT-The Long Lost Heads of Yojenkz
WTT-UpInSmoke
zSolarint-SAIN-ServerMod + waypoint + bigbrain

![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/172423396/a9c15a8e-021c-476b-aea6-4b1228be866c)
![image](https://github.com/space-commits/SPT-Realism-Mod-Client/assets/172423396/76a82956-7983-4fe8-9437-99e2ba784512)

**Comment by space-commits** [comment]
This is not the place for general support
